name: flutter_chat
description: "Basic chat flutter"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  bloc: ^7.1.0
  flutter_bloc: ^7.2.0
  equatable: ^2.0.3
  cloud_firestore: ^5.6.7
  firebase_storage: ^12.4.5
  image_picker: ^0.8.4
  sentry_flutter: ^8.14.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - lib/app/assets/
